title: Matt Harris Blog 
author: mattatbettervet
email: matt@bettervet.com
description: > # this means to ignore newlines until "baseurl:"
You can learn more about me anywhere!

# social links
twitter_username: harrisminer
github_username:  mattatbettervet

show_excerpts: true # set to false to remove excerpts on the homepage
